_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping
max_epochs: 100

accelerator: auto # automatically choose between CPU, GPU, TPU
devices: 1

strategy: ddp_find_unused_parameters_true #deepspeed_stage_1  #auto #deepspeed_stage_2 # deepspeed

benchmark: True # use torch.backends.cudnn.benchmark

# mixed precision for extra speed-up
# ref: https://lightning.ai/docs/pytorch/stable/common/precision_basic.html
precision: 32 #bf16-mixed

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False
