_target_: src.models.grad_icon_module.GradICONModule

name: GradICON_Registration

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0002
  betas: [0.9, 0.99]
  weight_decay: 0

scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  _partial_: true
  milestones: [250000, 300000]
  gamma: 0.5

netR_A:
  _target_: src.models.components.networks_define.define_R
  netR_type: gradicon
  batch_size: ${data.batch_size}
  dimension: 3
  init_type: 'normal'
  init_gain: 0.02

params: # Other params
  reverse: ${data.reverse} # A->B if False, B->A if True
  half_val_test: ${data.half_val_test}
  batch_size: ${data.batch_size}