_target_: src.models.stylegan2_module.StyleGAN2Module

name: StyleGAN2

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  betas: [0.5, 0.999]
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  _partial_: true
  milestones: [250000, 300000]
  gamma: 0.5

netG_A:
  _target_: src.models.components.networks_define.define_G
  netG_type: 'dam'
  input_nc: 1
  output_nc: 1
  feat_ch: 64
  demodulate: true
  # requires_grad: true

netD_A:
  _target_: src.models.components.networks_define.define_D
  input_nc: 1
  ndf: 64
  norm: 'instance'
  n_layers_D: 3
  init_type: 'normal' #'kaiming'

params: # Other params
  lambda_style: 5
  reverse: ${data.reverse} # A->B if False, B->A if True
  half_val_test: ${data.half_val_test}