_target_: src.models.unit_module.UnitModule

name: UNIT

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  betas: [0.5, 0.999]
  weight_decay: 0.0001


netG_A:
  _target_: src.models.components.networks_define.define_G
  netG_type: 'resnet_cat'
  input_nc: 1
  output_nc: 1
  nz: 0
  num_downs: 2
  n_res: 4
  ngf: 64
  norm: 'inst'
  nl_layer: 'relu'
  init_type: 'normal'


netG_B:
  _target_: src.models.components.networks_define.define_G
  netG_type: 'resnet_cat'
  input_nc: 1
  output_nc: 1
  nz: 0
  num_downs: 2
  n_res: 4
  ngf: 64
  norm: 'inst'
  nl_layer: 'relu'
  init_type: 'normal'


netD_A:
  _target_: src.models.components.networks_define.define_D
  input_nc: 1
  ndf: 64
  norm: 'instance'
  n_layers_D: 3
  init_type: 'normal'
  
netD_B:
  _target_: src.models.components.networks_define.define_D
  input_nc: 1
  ndf: 64
  norm: 'instance'
  n_layers_D: 3
  init_type: 'normal'
  
params: # Other params
  pool_size: 0
  lambda_content: 1
  lambda_kl: 0.001
  lambda_cycle: 1
  lambda_kl_cross: 0.001
  lambda_perceptual: 1
  lambda_contextual: 0