defaults:
  - model_checkpoint.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - custom_image_logging.yaml # added for logging images
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}-{val/fid_B.2f}-{val/nmi_B.2f}-{val/sharpness_B.2f}"
  monitor: "val/fid_B" # modified to look for best ssim
  save_top_k: 5
  mode: "min" # max, min
  save_last: True
  auto_insert_metric_name: True

model_summary:
  max_depth: 1
