"""
Batch MR-CT registration script for all patients in a test directory.
Registers CT to MR space using ANTsPy SyN algorithm for each patient.
"""
import sys
import argparse
import tempfile
import shutil
from pathlib import Path
from multiprocessing import Pool, cpu_count
import ants
import numpy as np


def normalize_robust(img_ants, pmin=1.0, pmax=99.0):
    """Robust intensity normalization to [0, 1] using percentiles."""
    arr = img_ants.numpy().astype(np.float32)
    lo, hi = np.percentile(arr, [pmin, pmax])
    arr = np.clip(arr, lo, hi)
    if hi - lo < 1e-8:
        arr = arr - lo
    else:
        arr = (arr - lo) / (hi - lo)
    return ants.from_numpy(
        arr, origin=img_ants.origin, spacing=img_ants.spacing, direction=img_ants.direction
    )


def maybe_resample_to_fixed(moving, fixed):
    """Resample moving image to fixed grid if needed."""
    return ants.resample_image_to_target(moving, fixed, interp_type="linear")


def cleanup_transform_files(reg_result):
    """Remove transform files generated by ANTs registration."""
    for key in ("fwdtransforms", "invtransforms"):
        for transform_path in reg_result.get(key, []):
            path = Path(transform_path)
            if path.exists():
                path.unlink()


def register_patient_wrapper(args_tuple):
    """Wrapper for multiprocessing."""
    patient_dir, mr_filename, ct_filename, output_filename, syn_type, tmp_root, idx = args_tuple
    patient_id = patient_dir.name
    success, message = register_patient(
        patient_dir, mr_filename, ct_filename, output_filename, syn_type, tmp_root
    )
    return idx, patient_id, success, message


def register_patient(
    patient_dir,
    mr_filename="mr_preprocess_-1to1.nii.gz",
    ct_filename="ct_preprocess_-1to1.nii.gz",
    output_filename="ct_syn.nii.gz",
    syn_type="SyN",
    tmp_root=None,
):
    """
    Register CT to MR space for a single patient.

    Args:
        patient_dir: Path to patient directory
        mr_filename: Name of MR file
        ct_filename: Name of CT file
        output_filename: Name of output file
        syn_type: Type of registration transform

    Returns:
        Tuple of (success: bool, message: str)
    """
    patient_dir = Path(patient_dir)

    mr_path = patient_dir / mr_filename
    ct_path = patient_dir / ct_filename
    output_path = patient_dir / output_filename
    deform_path = patient_dir / output_filename.replace('.nii.gz', '_deform.nii.gz')

    # Check if required files exist
    if not mr_path.exists():
        return False, f"MR file not found: {mr_path}"
    if not ct_path.exists():
        return False, f"CT file not found: {ct_path}"

    # Skip if both output and deformation field already exist
    if output_path.exists() and deform_path.exists():
        return True, f"Output already exists, skipping"

    try:
        # Load images
        fixed = ants.image_read(str(mr_path))
        moving = ants.image_read(str(ct_path))

        # Store original MR orientation
        fixed_direction = fixed.direction

        # Resample moving to fixed grid
        moving_rs = maybe_resample_to_fixed(moving, fixed)

        # Robust normalization
        fixed_p = normalize_robust(fixed)
        moving_p = normalize_robust(moving_rs)

        tmp_parent = Path(tmp_root) if tmp_root else patient_dir / ".ants_tmp"
        tmp_parent.mkdir(parents=True, exist_ok=True)

        # Keep ANTs temp files out of /tmp quota and clean them after each case.
        with tempfile.TemporaryDirectory(dir=str(tmp_parent)) as tmp_dir:
            outprefix = str(Path(tmp_dir) / "ants_")

            # Registration
            reg = ants.registration(
                fixed=fixed_p,
                moving=moving_p,
                type_of_transform=syn_type,
                outprefix=outprefix,
                verbose=False
            )

            # Apply transforms to original moving image
            warped = ants.apply_transforms(
                fixed=fixed,
                moving=moving,
                transformlist=reg["fwdtransforms"],
                interpolator="linear"
            )

            # Save deformation field before cleanup
            # fwdtransforms[0] is the deformation field (.nii.gz)
            if reg["fwdtransforms"]:
                deform_src = Path(reg["fwdtransforms"][0])
                if deform_src.exists() and deform_src.suffix == '.gz':
                    shutil.copy2(str(deform_src), str(deform_path))

            cleanup_transform_files(reg)

        # Preserve MR orientation
        warped.set_direction(fixed_direction)

        # Save warped CT
        ants.image_write(warped, str(output_path))

        return True, f"Registration completed successfully"

    except Exception as e:
        return False, f"Registration failed: {str(e)}"


def main():
    parser = argparse.ArgumentParser(
        description="Batch register CT to MR space for all patients across multiple splits"
    )
    parser.add_argument(
        "--base_dir",
        type=str,
        default="/SSD5_8TB/Daniel/09_registformer_hugging_face/mem_eff_registformer/data/synthrad2023_mr-ct_pelvis",
        help="Base directory containing train/val/test/try folders"
    )
    parser.add_argument(
        "--splits",
        type=str,
        nargs="+",
        default=["train", "val", "test", "try"],
        help="List of splits to process"
    )
    parser.add_argument(
        "--mr_filename",
        type=str,
        default="ct_stage1_jbhi.nii.gz",
        help="Name of MR file (fixed image)"
    )
    parser.add_argument(
        "--ct_filename",
        type=str,
        default="ct_preprocess_jbhi.nii.gz",
        help="Name of CT file (moving image)"
    )
    parser.add_argument(
        "--output_filename",
        type=str,
        default="ct_syn_stage1_jbhi.nii.gz",
        help="Name of output file"
    )
    parser.add_argument(
        "--syn_type",
        type=str,
        default="SyN",
        help="Type of registration transform"
    )
    parser.add_argument(
        "--num_workers",
        type=int,
        default=1,
        help="Number of parallel workers (default: 1, use -1 for all CPUs)"
    )
    parser.add_argument(
        "--tmp_root",
        type=str,
        default=None,
        help="Root directory for ANTs temporary files (default: <patient_dir>/.ants_tmp)"
    )

    args = parser.parse_args()

    # Determine number of workers
    if args.num_workers == -1:
        num_workers = cpu_count()
    else:
        num_workers = args.num_workers

    base_dir = Path(args.base_dir)

    # Verify base directory exists
    if not base_dir.exists():
        print(f"Error: Base directory does not exist: {base_dir}")
        sys.exit(1)

    print("\n" + "=" * 80)
    print("Batch MR-CT Registration (Multi-Split)")
    print("=" * 80)
    print(f"Base directory: {base_dir}")
    print(f"Splits: {', '.join(args.splits)}")
    print(f"MR filename (fixed): {args.mr_filename}")
    print(f"CT filename (moving): {args.ct_filename}")
    print(f"Output filename: {args.output_filename}")
    print(f"Number of workers: {num_workers}")
    print("=" * 80 + "\n")

    # Global counters
    total_success = 0
    total_skip = 0
    total_fail = 0
    all_failed_patients = []

    # Process each split
    for split in args.splits:
        split_dir = base_dir / split

        if not split_dir.exists():
            print(f"Warning: Split directory does not exist, skipping: {split_dir}\n")
            continue

        # Get all patient directories in this split
        patient_dirs = sorted([d for d in split_dir.iterdir() if d.is_dir()])

        if not patient_dirs:
            print(f"Warning: No patient directories found in {split}, skipping\n")
            continue

        print(f"\n{'=' * 80}")
        print(f"Processing split: {split} ({len(patient_dirs)} patients)")
        print(f"{'=' * 80}")

        # Process each patient in this split
        success_count = 0
        skip_count = 0
        fail_count = 0

        # Prepare arguments for parallel processing
        task_args = [
            (
                patient_dir,
                args.mr_filename,
                args.ct_filename,
                args.output_filename,
                args.syn_type,
                args.tmp_root,
                i
            )
            for i, patient_dir in enumerate(patient_dirs, 1)
        ]

        # Process patients (parallel or sequential)
        if num_workers > 1:
            with Pool(num_workers) as pool:
                results = pool.map(register_patient_wrapper, task_args)
        else:
            results = [register_patient_wrapper(arg) for arg in task_args]

        # Display results in order
        for idx, patient_id, success, message in sorted(results, key=lambda x: x[0]):
            print(f"[{idx:2d}/{len(patient_dirs)}] {split}/{patient_id}...", end=" ")

            if success:
                if "skipping" in message.lower():
                    print(f"⊘ {message}")
                    skip_count += 1
                else:
                    print(f"✓ {message}")
                    success_count += 1
            else:
                print(f"✗ {message}")
                fail_count += 1
                all_failed_patients.append(f"{split}/{patient_id}: {message}")

        # Split summary
        print(f"\nSplit '{split}' summary: Success={success_count}, Skipped={skip_count}, Failed={fail_count}\n")

        total_success += success_count
        total_skip += skip_count
        total_fail += fail_count

    # Final summary
    print("\n" + "=" * 80)
    print("Overall Summary")
    print("=" * 80)
    print(f"Total Successful: {total_success}")
    print(f"Total Skipped: {total_skip}")
    print(f"Total Failed: {total_fail}")

    if all_failed_patients:
        print("\nAll failed patients:")
        for patient in all_failed_patients:
            print(f"  - {patient}")

    print("=" * 80)

    if total_fail > 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
